name: git_view
description: Git View allows you to view the git history of your repository.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  fluttericon: ^2.0.0
  github: ^9.7.0
  http: ^0.13.5
  intl: ^0.17.0
  oauth2: ^2.0.1
  url_launcher: ^6.1.6
  #window_to_front:
  #  path: ./window_to_front

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
